### ISSUE TITLE
Not compatible with 1.52.1

### ISSUE THREAD

**Issue by DemmyDemon** [Traineratwot/vscode-stationeers-ic10#1]
I am unable to install 'traineratwot.stationeers-ic10' extension because it is not compatible with the current version of VS Code (version 1.52.1).

**Comment by Traineratwot** [comment]
![image](https://user-images.githubusercontent.com/41589091/112623823-e1f4d400-8e3d-11eb-9ed2-bc03d649ccfa.png)
 
Update u vs code :)

**Comment by DemmyDemon** [comment]
Yep, that did it. My bad, I thought it was _because_ I updated.
Too bad VSC doesn't give a more verbose error, because morons like me are _all over_ the internet!

**Comment by Traineratwot** [comment]
Good  :)
