### ISSUE TITLE
Recognizing variables broken

### ISSUE THREAD

**Issue by Helfima** [Traineratwot/vscode-stationeers-ic10#22]
with version 0.02
![image](https://user-images.githubusercontent.com/20326713/116388477-2946f980-a81c-11eb-940c-bff32f8b20aa.png)
and in next versions
![image](https://user-images.githubusercontent.com/20326713/116388640-53002080-a81c-11eb-84a3-239b556dda41.png)

**Comment by Traineratwot** [comment]
I use Monokai theme
![image](https://user-images.githubusercontent.com/41589091/116393357-35d24e80-a82a-11eb-973f-9475e22af2b4.png)

standart theme not support all keywords type

**Comment by Helfima** [comment]
oh that work
![image](https://user-images.githubusercontent.com/20326713/116431661-4691bd00-a848-11eb-9704-1a31b8a55f83.png)
there are new variable, I will create another issue with all variables asap
