### ISSUE TITLE
Missing batch instruction

### ISSUE THREAD

**Issue by Helfima** [Traineratwot/vscode-stationeers-ic10#23]
there are 2 new batch instruction, lb and sb
![image](https://user-images.githubusercontent.com/20326713/116389747-9b6c0e00-a81d-11eb-9289-f73f19e71103.png)

**Comment by Traineratwot** [comment]
Ok i will do it soon

**Comment by Traineratwot** [comment]
I never use this function, send me please any code wich that use lr and sb :)

**Comment by Helfima** [comment]
yes, type is the PrefabHash
![image](https://user-images.githubusercontent.com/20326713/116548591-bfe6e980-a8f4-11eb-8c9c-198634968937.png)
Prefabhash is a positive or negative integer
in this sample I put the prefabhash in the r2 to use in the batch writer that set horizontal and vertical of solar panel to folow sun.
```
# Solar Panel Control
# Sensor: port see south
# Solar Panel: port see west
alias Sensor d0
alias SolarPanel d1
alias DisplayHealth d3
alias DisplayWatt d4
s Sensor Mode 0
s DisplayHealth Mode 1
s DisplayWatt Mode 0
start:
l r0 Sensor Horizontal
l r1 Sensor Vertical
l r2 SolarPanel PrefabHash
l r3 SolarPanel Maximum
lb r4 r2 Charge 0 # read average power
lb r5 r2 Charge 1 # read sum power
sub r1 75 r1
div r1 r1 1.5
div r4 r4 r3
sb r2 Horizontal r0 # r2 hash of Solar Panel
sb r2 Vertical r1 # r2 hash of Solar Panel
s DisplayHealth Setting r4
s DisplayWatt Setting r5
j start
```

**Comment by Traineratwot** [comment]
I did. you can update the extension :). and i add more snippets and description

**Comment by Traineratwot** [comment]
And i add secret function for better debug, like `#_move`  `#_l`  `#_s`

**Comment by Helfima** [comment]
i don't see changement
![image](https://user-images.githubusercontent.com/20326713/116691615-54b41a80-a9bb-11eb-94a2-36c9a91cb18f.png)

**Comment by Traineratwot** [comment]
Oh, I forget add that in highlight list

**Comment by Traineratwot** [comment]
Hey, it you develop helmod for factorio :) good job bro Thanks ). I develop mod factorio too `X100_assembler` if you now

**Comment by Helfima** [comment]
yes I am the helmod creator :)
I like the building game
if I did DSP_Helmod for Dyson Sphere Program too

I mean all command should be in the same color
![image](https://user-images.githubusercontent.com/20326713/116730046-46302800-a9e8-11eb-9e1b-7d7978e02480.png)
![image](https://user-images.githubusercontent.com/20326713/116730110-5d6f1580-a9e8-11eb-9b35-446df0dbdaeb.png)

**Comment by Traineratwot** [comment]
I fixed it. now all function has one color. and i colorize variable (r1,rrr1, d0 ....) :)
