### ISSUE TITLE
Debugger not working

### ISSUE THREAD

**Issue by kirill2400** [Traineratwot/vscode-stationeers-ic10#25]
Debugger not working, just run and after a few seconds stops
![image](https://user-images.githubusercontent.com/30482699/116575981-ce92c800-a917-11eb-9e9f-d570e9bd1ec1.png)

**Comment by kirill2400** [comment]
only 0.0.7 working, 0.0.8 and 0.0.9 not working

**Comment by Traineratwot** [comment]
Thanks, i fix it in 0.0.12 :)
