### ISSUE TITLE
bnez not working properly in debugger

### ISSUE THREAD

**Issue by kirill2400** [Traineratwot/vscode-stationeers-ic10#27]
![image](https://user-images.githubusercontent.com/30482699/116720428-d8363180-a9e4-11eb-887b-8759c4392db5.png)
r0 = 0, bnez working as beqz in debugger and description for bnez maybe incorrect

**Comment by Traineratwot** [comment]
Пришли пожалуйста этот код мне для тестов, я проверил у себя, все работает. Описание поправил

**Comment by kirill2400** [comment]
# Охлаждение.
# Чип 6 входов
# 
# Датчик т контура
# Датчик т воздуха
# Датчик т гидро
# Вентиль охлад контур
# Вентиль охлад воздух
# Вентиль охлад гидро
# 
# Каждый к каждому, по верхней и нижней уставке. Включается вентиль если т макс, выключается если мин.
# газы 0-5
# воздух 22-26
# гидро 30-40
define lowContur 273
define highContur 278
define lowAir 295
define highAir 299
define lowHydro 303
define highHydro 313

define ActiveVentHash -1129453144
define forEnable 10000
define forDisable 200

alias counter r10
alias activeVentState r11
alias sensorContur d0
alias sensorAir d1
alias sensorHydro d2
alias ventContur d3
alias ventAir d4
alias ventHydro d5

move counter 0
move activeVentState 0

main:
jal checkContur
jal checkAir
jal checkHydro
jal processFilterVents
s db Setting counter
j main

checkContur:
    l r0 sensorContur Temperature
    brlt r0 highContur 2
    s ventContur On 1
    brgt r0 lowContur 2
    s ventContur On 0
j ra

checkAir:
    l r0 sensorAir Temperature
    brlt r0 highAir 2
    s ventAir On 1
    brgt r0 lowAir 2
    s ventAir On 0
j ra

checkHydro:
    l r0 sensorHydro Temperature
    brlt r0 highHydro 2
    s ventHydro On 1
    brgt r0 lowHydro 2
    s ventHydro On 0
j ra

processFilterVents:
    sb ActiveVentHash Lock 1
    bnez activeVentState processOff
processOn:
    add counter counter 1
    blt counter forEnable ra
    sb ActiveVentHash On 1
    move activeVentState 1
    move counter 0
processOff:
    add counter counter 1
    blt counter forDisable ra
    sb ActiveVentHash On 0
    move activeVentState 0
    move counter 0
j ra

**Comment by Traineratwot** [comment]
Я поправил, проблема была не в `bnez` а  в `jal` он сначала делал переход а потом записывал в r17 :) чушь получалась
