### ISSUE TITLE
Initial Value of registers

### ISSUE THREAD

**Issue by kirill2400** [Traineratwot/vscode-stationeers-ic10#28]
В при первом запуске чипа в игре в рабочих регистрах лежат не совсем нули, то есть тут как повезете либо там ноль либо волшебное огромное число, я полчаса разбирался что не так пока предварительно не обнулил регистры, может стоит в дебаггере симулировать мусор в регистрах дабы заставлять кодера сразу очищать?

**Comment by Traineratwot** [comment]
Ого :) не знал что там еть мусор. в дебаггер наверное добавлять не стоит но можно добавить подсказку при создании файла c обнулениями регистра, но его я добавлю чуть по позже. 

К тому же скорее всего этот мусор просто остался от предыдущей программы в чипе

**Comment by kirill2400** [comment]
у меня в сокетах всегда только один чип, я их не рядом с компьютером ставлю а сразу где нужно чтобы микроконтроллер не таскать туда сюда, и вот в r10-15 могло быть либо ноль либо 1 по логике моей программы, но было так что один или два этих регистра имели значения то 2768.... то -6732....

**Comment by kirill2400** [comment]
на самом деле стоит программой проверить состояние каждого регистра на старте, и убедиться до конца

**Comment by Traineratwot** [comment]
Я сейчас пытаюсь написать форматировщик для ic10, можно сделать так чтобы при форматирование в начло программы добавлялись `move r{n} 0` для каждой используемой переменно. :)

**Comment by Traineratwot** [comment]
https://www.youtube.com/watch?v=klg56OXbM3Q вот

**Comment by kirill2400** [comment]
А если в alias использовать тоже поймет?

**Comment by kirill2400** [comment]
Хорошая работа, но это вряд ли будет работать где я циклом с r10-15 обнуляю, но спасибо!

**Comment by Traineratwot** [comment]
alias поймет.
Ну по крайней мере напомнит что нужно очищать переменные :)
