### ISSUE TITLE
Debugger not like usual IDE

### ISSUE THREAD

**Issue by kirill2400** [Traineratwot/vscode-stationeers-ic10#29]
В дебаггере желтая строка выделяют строчку которую он уже только что выполнил, в обычных Rider VS Studio желтой помечается строка которая вот-вот выполнится, если мы сделаем шаг. Это довольно неудобно, что на желтой команда уже выполнена.
Так, например, эта команда никогда не выделится желтым: bleal pressure MinPressure disableTankCode
Так как он сразу выполняет переход и желтым окрашивается строка с меткой disableTankCode

**Comment by Traineratwot** [comment]
Поправил, в следующем обновлении выйдет

**Comment by Traineratwot** [comment]
обновление вышло
