### ISSUE TITLE
Баг дебаггера, некоторые команды не исполняются

### ISSUE THREAD

**Issue by kirill2400** [Traineratwot/vscode-stationeers-ic10#30]
![image](https://user-images.githubusercontent.com/30482699/116777136-796cc880-aa75-11eb-8309-abf8d8472702.png)
первая итерация отрабатывает нормально, на второй итерации он прыгает в начало цикла и пропускает первую строчку цикла не выполняя её

**Comment by kirill2400** [comment]
причем 64 строчка подсвечивала желтым, перед этим brlt не подсвечивалась, но на это есть отдельный топик. Так вот, она подсвечивалась но в итоге не выполнила команду div

**Comment by kirill2400** [comment]
![image](https://user-images.githubusercontent.com/30482699/116777260-51ca3000-aa76-11eb-8ba9-0ba3f0e38d08.png)
and не отрабатывает с такой ошибкой

**Comment by kirill2400** [comment]
![image](https://user-images.githubusercontent.com/30482699/116777759-c7ce9700-aa76-11eb-98cb-d51c96404a5f.png)
у меня некоторые функции не отрабатывают вообще

**Comment by kirill2400** [comment]
`define AirMaxPressure 10000
define FuelMaxPressure 10000
define HydroMaxPressure 10000

alias mixerAir d0
alias mixerFuel d1
alias mixerHydro d2
alias airTank d3
alias fuelTank d4
alias hydroTank d5

alias code r0
alias returnValue r1

main:
move code 2121111111
div code code 1000000
trunc code code

jal checkTemp
beqz returnValue main

push 0
jal checkMixer
s mixerAir On returnValue

push 1
jal checkMixer
s mixerFuel On returnValue

push 2
jal checkMixer
s mixerHydro On returnValue

j main

checkTemp:
mod r2 code 2
sne returnValue r2 1
j ra

checkMixer:
pop r5
move r4 -1
move r2 code
div r2 r2 10
add r4 r4 1
brlt r4 r5 -2
trunc r2 r2

mod r2 r2 2
sne returnValue r2 1
beqz returnValue ra

add r4 r5 3
l r3 dr4 Pressure
slt r3 r3 AirMaxPressure
and returnValue returnValue r3
j ra`
Вот проблемный код, там ошибок 3 как минимум

**Comment by Traineratwot** [comment]
Исправил
