### ISSUE TITLE
Recognizing variables II

### ISSUE THREAD

**Issue by Helfima** [Traineratwot/vscode-stationeers-ic10#32]
hello
some value missing from this issue #24
![image](https://user-images.githubusercontent.com/20326713/118109386-6943da00-b3e1-11eb-99a9-b890afa1126e.png)
![image](https://user-images.githubusercontent.com/20326713/118109407-74970580-b3e1-11eb-8126-496f3b5d9dc0.png)

**Comment by Traineratwot** [comment]
send me this text please

**Comment by Helfima** [comment]
the text is in this issue #24

**Comment by Traineratwot** [comment]
i fix it
