### ISSUE TITLE
working with stack

### ISSUE THREAD

**Issue by Helfima** [Traineratwot/vscode-stationeers-ic10#33]
registers are the same from r0 at r17, r16 is not a array but the stack position
see https://stationeering.com/tools/ic
stack is a special component, the length of array is 512

sp (r16) is the stack position label and not work in debug:
when a value is push sp=sp+1
when a value is pop sp=sp-1
to put value in entry 5, move sp 5 and push value
to get value entry 5, move sp 6 and pop value

Script test:
```
# Alias Register
alias Signal r4
alias Temp r10
alias IsSkip r13
alias Skip r14 #Stack index

move Skip 0
move IsSkip 0

start:
s db Setting -99999
yield
s db Setting Skip
yield
# Add 3 values in stack
move Signal 100
jal addSkip
move Signal 101
jal addSkip
move Signal 102
jal addSkip
# Set test value
move Signal 100
# Execute the test
jal checkSkip
s db Setting IsSkip
sleep 2
j start

addSkip:
s db Setting -11
yield
add Skip Skip 1
move sp Skip
push Signal
j ra

checkSkip:
s db Setting -10
yield
beq Skip -1 ra
move IsSkip 0
move sp Skip
ble sp 0 ra # End stack
pop Temp # Read stack value
brne Temp Signal -2
move IsSkip 1
j ra
```

**Comment by Helfima** [comment]
the proposal for debug
![image](https://user-images.githubusercontent.com/20326713/118116152-37834100-b3ea-11eb-9859-eade36e5af70.png)

**Comment by Traineratwot** [comment]
Fix it
