### ISSUE TITLE
IcX не воспринимает отрицательные значения

### ISSUE THREAD

**Issue by kirill2400** [Traineratwot/vscode-stationeers-ic10#37]
if recipeHash == -1897868623
    d0.Open = 1
end

Хеш у которого отрицательное значение он записывает как единицу в результате, приходится искать и подставлять самому

**Comment by kirill2400** [comment]
А ещё я не могу в icx написать алиасы, так он не компилит

**Comment by Traineratwot** [comment]
icX сам распоряжается переменными, используй `var` и `const`. Насчет hash я посмотрю

**Comment by kirill2400** [comment]
а как мне сделать алиас для портов? неужели var Furnace = d0

**Comment by Traineratwot** [comment]
Хороший вопрос ) видимо это придется допилить. )  я сделал только такой вариант ```d0.Settings = 1```

**Comment by kirill2400** [comment]
а будет передача параметров в функции?))

**Comment by kirill2400** [comment]
А как мне в цикле по всем портах проходить? то есть d(счетчик).On = 1 к примеру

**Comment by kirill2400** [comment]
Составные условия?)

**Comment by Traineratwot** [comment]
```а будет передача параметров в функции?))``` нет не будет в ic10 нет возможности изолировать переменные это просто не возможно :)
```А как мне в цикле по всем портах проходить? то есть d(счетчик).On = 1 к примеру```` я еще думаю как это лучше сделать, но если все Девайсы одинаковые то можно использовать пакетную запись `d(5438547545).Setting = b` с обновлением появится )
```Составные условия?)``` могу сделать только с `И` с обновлением появится )

**Comment by Traineratwot** [comment]
https://discord.gg/GAK42dwH Го в дискорд.

**Comment by Traineratwot** [comment]
````
var x = 1
d[x].Setting = 4
var t = d[x].Setting
var a = d[x].slot(5).Setting
```
```
move r0 1
s dr0 Setting 4
l r1 dr0 Setting
ls r2 dr0 5 Setting
```
