### ISSUE TITLE
[icX][Idea]: Использование define

### ISSUE THREAD

**Issue by Kopnu** [Traineratwot/vscode-stationeers-ic10#39]
Не нашёл примеров интерпретации констант (`define`). Интуитивные пробы ничего не дали. 
Иногда есть необходимость писать код для других людей и им проще поправить одну константу чем искать её в коде.

icX:
```
use aliases
define PI = 3.14
d0.Setting = PI
```
Ожидаемый результат ic10:
```
define PI 3.14
s d0 Setting PI
```

**Comment by Traineratwot** [comment]
use constants
