### ISSUE TITLE
VS Code marks sp as an invalid parameter

### ISSUE THREAD

**Issue by joshuareeves** [Traineratwot/vscode-stationeers-ic10#41]
**Describe the bug**
VS Code highlights the use of the default "sp" label for r16 register as an error:
"invalid parameter: sp, must be "R/N"(ic10_diagnostic)"

**To Reproduce**
1. Write a line to clear the stack pointer: "move sp 0"
2. See that VS Code reports this as an error and underlines the "sp" with a red squiggly line.

**Expected behavior**
VS Code should recognize "sp" as a valid default label, in the same way it recognizes "ra" as a valid label.

**Screenshots**
![image](https://user-images.githubusercontent.com/16243352/128430780-92240be0-606a-488e-bc1a-e871e6160780.png)

**Comment by Traineratwot** [comment]
fixed. update the extension :)

**Comment by joshuareeves** [comment]
Awesome! Thanks!
