### ISSUE TITLE
Stack memory don't work

### ISSUE THREAD

**Issue by Helfima** [Traineratwot/vscode-stationeers-ic10#42]
**Describe the bug**
Regiter r16 is not a array but the Stack Pointer
The stack is another memory in the IC

In your debug r16 is a array
![image](https://user-images.githubusercontent.com/20326713/128547277-486ed7d0-4434-4af8-8cae-7f553e2028bf.png)

In the IC you have
Device: d0 at d5
Register: r0 at r17
Stack: array length 512

you can see here https://stationeering.com/tools/ic
![image](https://user-images.githubusercontent.com/20326713/128547007-e33250fc-7a27-4814-aa4c-d413c6a424af.png)
SP value 5
![image](https://user-images.githubusercontent.com/20326713/128547057-80ea3121-4ce8-4be0-b79a-4990005146bb.png)
We can see where is the SP in the Stack

**To Reproduce**
This code must put -1301215609 in r0
```
# Tutorial: stack
# Alias Register
alias Hash r0
alias Choose r1 # Dial setting
start:
yield
move Choose 5
jal getValues
s db Setting Hash
j start

getValues:
move sp 0
push 2134647745 # Lead Ingot
push 252561409 # Charcoal
push -404336834 # Copper Ingot
push -929742000 # Silver Ingot
push 226410516 # Gold Ingot
push -1301215609 # Iron Ingot
push -1406385572 # Nickel Ingot
push -290196476 # Silicon Ingot
push -654790771 # Steel Ingot
push 502280180 # Electrum Ingot
push -82508479 # Solder Ingot
push 1058547521 # Constantan Ingot
push -297990285 # Invar Ingot
push 412924554 # Astroloy Ingot
push -787796599 # Inconel Ingot
push 156348098 # Waspaloy Ingot
push 1579842814 # Hastelloy Ingot
push -1897868623 # Stellite Ingot
add sp Choose 1 # Add 1 to read value
pop Hash
j ra
```

becareful with stack command
![image](https://user-images.githubusercontent.com/20326713/128547820-08acabfc-7260-432a-b460-dc3dba2b6d2c.png)

To put a value at the index 0:
```
move sp 0
push 1234
```
To read a value at the index 0 you must move the pointer index+1:
```
add sp 0 1
pop r0
```

**Comment by Traineratwot** [comment]
Thank, for your feedback, i was stupid :). I update Stack system and add `foreach` to icX.

**Comment by Helfima** [comment]
hi
that work fine :)
