### ISSUE TITLE
Instruction with end "z" dont work

### ISSUE THREAD

**Issue by Helfima** [Traineratwot/vscode-stationeers-ic10#45]
**Describe the bug**
Instruction with end "z" dont work

**To Reproduce**
```
start:
move r0 0
breqz r0 2
move r0 1
move r0 2
move r0 3
brgtz r0 -2
j start
```
![image](https://user-images.githubusercontent.com/20326713/144997402-0d39a517-ab83-4484-b72d-d19435af503d.png)
line 3 must jump at line 5
line 7 must jump at line 5

**Expected behavior**
the instruction with end "z" compare the value with zero there are only one argument to compare

**Comment by Traineratwot** [comment]
Yes, what a stupid mistake on my part :)
Fixed an update coming soon.
15 minutes.

**Comment by Helfima** [comment]
thx that work
