### ISSUE TITLE
Max Function does not return maximal value 

### ISSUE THREAD

**Issue by fwolle30** [Traineratwot/vscode-stationeers-ic10#46]
**Describe the bug**
max function does not work

**To Reproduce**
```
alias test r0
move test 0
max test test 1
s db Setting test
j 0
```

**Expected behavior**
test should be 1

**Comment by fwolle30** [comment]
The same goes for min

```
alias test r0
move test 0
min test test -1
s db Setting test
j 0
```

should yield -1

**Comment by Traineratwot** [comment]
Thanks, I Corrected It. You can update the extension
