### ISSUE TITLE
Variable is missing Seeding

### ISSUE THREAD

**Issue by tolyaik** [Traineratwot/vscode-stationeers-ic10#47]
Variable slot is missing "Seeding"
------------------------------------
Отсутствует переменная слота "Seeding" 

![Снимок экрана 2021-12-28 191552](https://user-images.githubusercontent.com/6270128/147565474-5d4ffa39-1bd3-4b73-838f-bdb3475b3aa7.jpg)

**Comment by Traineratwot** [comment]
в первые ее вижу, на wiki не нашел. можешь описать что это? и я добавлю

**Comment by tolyaik** [comment]
https://stationeers.fandom.com/ru/wiki/%D0%93%D0%B8%D0%B4%D1%80%D0%BE%D0%BF%D0%BE%D0%BD%D0%BD%D0%B0%D1%8F_%D1%83%D1%81%D1%82%D0%B0%D0%BD%D0%BE%D0%B2%D0%BA%D0%B0

 
>Вторник, 28 декабря 2021, 20:20 +07:00 от Kirill < ***@***.*** >:
> 
> 
>в первые ее вижу, на wiki не нашел. можешь описать что это? и я добавлю
>—
>Reply to this email directly,  view it on GitHub , or  unsubscribe .
>Triage notifications on the go with GitHub Mobile for  iOS or  Android .
>You are receiving this because you authored the thread. Message ID:  <Traineratwot/vscode-stationeers-ic10/issues/47/1002102553 @ github . com> 
 
 
--
С уважением, Анатолий Иконников

**Comment by Traineratwot** [comment]
Добавил

**Comment by tolyaik** [comment]
Спасибо!
