### ISSUE TITLE
new mips math command "atan2" is unknown

### ISSUE THREAD

**Issue by mariokoehler** [Traineratwot/vscode-stationeers-ic10#50]
**Describe the bug**
The so called "just in time" update to the game introduced the new mathematical function "atan2" to the mips command set.

read about it in the patch notes here:

https://www.reddit.com/r/Stationeers/comments/qbqzyi/the_just_in_time_update_has_landed/

the VS code extension marks this command as an unknown function

**To Reproduce**

this example tries to determine the compass heading the player is currently looking at:

```
use aliases
alias Suit db

var velocityRelativeX = Suit.VelocityRelativeX
var velocityRelativeZ = Suit.VelocityRelativeZ
var heading = 0
atan2 heading velocityRelativeX velocityRelativeZ
div heading heading 3.14
mul heading heading 180

```

it gets compiled into this:

```
alias velocityRelativeX r0
alias velocityRelativeZ r1
alias heading r2
alias Suit db
l velocityRelativeX Suit VelocityRelativeX
l velocityRelativeZ Suit VelocityRelativeZ
move heading 0
atan2 heading velocityRelativeX velocityRelativeZ
div heading heading 3.14
mul heading heading 180

```

and VS Code marks the line that contains the "atan2" as a red underlined unknown function.

**Expected behavior**
function is recognized as a valid one

**Screenshots**
![screenshot](https://user-images.githubusercontent.com/63335677/152679079-84d35c08-6830-4589-abce-a2dbd7ef9b6a.jpg)

**Additional context**
n/a

**Comment by mariokoehler** [comment]
0.4.9 is still the most recent version i can see...i'll check back in a while, maybe it takes a moment to "propagate" and become visible

**Comment by Traineratwot** [comment]
try again, i getted mail from vs about update

**Comment by mariokoehler** [comment]
It was my own mistake, I was still logged into my companies VPN when i tried it, and they have some access restrictions in place. Without the VPN i was able to see and install it no problem.

atan2 is now recognized as a valid function. yay! :-)

Thanks again for your effort and your contribution to the Stationeers community!
