### ISSUE TITLE
icX_diagnostic treats "<=" and ">=" as errors

### ISSUE THREAD

**Issue by MegrezZhu** [Traineratwot/vscode-stationeers-ic10#52]
**Describe the bug**
icX_diagnostic treats "<=" and ">=" as errors:
![image](https://user-images.githubusercontent.com/21364971/184266040-0fb92667-a2a6-4430-abcc-3b93482dd24f.png)
![image](https://user-images.githubusercontent.com/21364971/184266016-d1a96b28-5ace-4e46-9494-90ae9d135441.png)

This is likely caused by the recent change in `icX.diagnostics.ts`:
https://github.com/Traineratwot/vscode-stationeers-ic10/blob/faf7dfceec4cc1d92c260c81e3f758976e642985/core/icX.diagnostics.ts#L283-L287

**To Reproduce**
```
var a = 1
if a == 0 # linter happy
	
end
if a <= 1 # linter unhappy
	
end
```

**Expected behavior**
No error message.

**Additional context**

**Comment by Traineratwot** [comment]
Year. it`s my mistake :). Thank you for taking your time to figure out my code. 

I have updated the extension

**Comment by Traineratwot** [comment]
if you are interested, we can do localization for China together

**Comment by MegrezZhu** [comment]
Thanks for the quick fix :) And I have to say this extension (and icX) is awesome!

As for translation, I'm playing the English version of the game as well, so might not be a very good person for localization. Though, I found `Stationeers/rocketstation_Data/StreamingAssets/Language/<english|russian|chinese|etc.>.xml` may be good reference for tooltip translation, there are translations for all logic variable descriptions - some regex based replacing could help :)
