### ISSUE TITLE
New device variables are unknown

### ISSUE THREAD

**Issue by KapiCytryna** [Traineratwot/vscode-stationeers-ic10#54]
Throttle, Rpm, Stress, CombustionLimiter and other device variables are unknown.

**Comment by Traineratwot** [comment]
Unfortunately, it is impossible to pull the ic10 structure out of the game files, and I don't want to do it manually :).
I will create a web tool where the community will be able to add the missing descriptions by itself, I will only have to check and release updates.

Go to discord, where I will notify you when I make this tool.
https://discord.com/invite/KSVjXufkA9
