### ISSUE TITLE
Incorrect compilation of IF...ELSE...END

### ISSUE THREAD

**Issue by Vislor** [Traineratwot/vscode-stationeers-ic10#55]
If I write this icx:

```
if r0 < 0.05
    r0 = 1
else
    r0 = 0
end
```

The compiled ic10 output is the following, which is incorrect:

```
sltz r15 r0
beqz r15 if0else
move r0 1
j if0exit
if0else:
move r0 0
if0exit:
```

Not sure why it is using `sltz r15 0`  when it should be compiled to `slt r15 r0 0.05`.

**Comment by Traineratwot** [comment]
Thanks. I fixed this in v0.6.11
